export function emptyItem() {
    return {
        id: 0, parentId: null, type: 1, title: '', regions: [], responsible: '', progress: '',
        progressColor: '', dateStart: '', dateEnd: '', tags: [], expanded: true, done: false,
        pinned: 0, team: [], category: [], anspruch: [], color: '',
    }
}
export function getItems() {
    let ls_ = localStorage.getItem('items')
    if (ls_) {
        ls_ = JSON.parse(ls_)
    } else {
        ls_ = [
            Object.assign(emptyItem(),{
                id: 1, type: 9,
                title: 'Initiative: Softwarelösungen für kleine Unternehmen',
                regions: ['Führungsteam'],
                responsible: 'S. Fischer',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                color: 'blue',
            }),
            Object.assign(emptyItem(),{
                id: 2, parentId: 1,
                title: 'Hauptziel: Erfolgreiche Einführung eines neuen Softwareprodukts auf dem Markt',
                regions: ['Produktionsleitung', 'Marketing', 'Verkauf'],
                responsible: 'J. Depont',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                tags: ['KC', 'OKR'],
                done: true,
                pinned: 5,
                color: 'green',
            }),
            Object.assign(emptyItem(),{
                id: 3, parentId: 2, type: 2,
                title: 'Etappenziel 1: Marktforschung',
                regions: ['Verkauf'],
                responsible: 'I. Horvat',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                color: 'orange',
            }),
            Object.assign(emptyItem(),{
                id: 4, parentId: 3, type: 3,
                title: 'Design und Prototyping des Produkts',
                regions: ['Logistik'],
                responsible: 'M. Benedetto',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '', dateEnd: '23.12.2025',
                tags: ['KC'],
                expanded: false,
                color: 'purple',
            }),
            Object.assign(emptyItem(),{
                id: 5, parentId: 3, type: 6,
                title: 'Erstellung der Marketingstrategie',
                regions: ['Qualiätssicherung'],
                responsible: 'K. Schneider',
                progress: '-10%',
                progressColor: 'red',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                expanded: false,
                done: true,
                color: 'red',
            }),
            Object.assign(emptyItem(),{
                id: 6, parentId: 2, type: 4,
                title: 'Etappenziel 2: Produktentwicklung und Usability-Tests',
                regions: ['Social Media', 'Verkauf', 'Marketing'],
                responsible: 'S. Fischer',
                progress: '-10%',
                progressColor: 'red',
                dateStart: '',dateEnd: '23.12.2025',
                color: 'cyan',
            }),
            Object.assign(emptyItem(),{
                id: 7, parentId: 6, type: 5,
                title: 'Erarbeitung des ersten Softwareprototyps...',
                regions: ['Marketing', 'Verkauf'],
                responsible: 'J. Depont',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '6.6.2025', dateEnd: '23.12.2025',
                expanded: false,
                color: 'blue',
            }),
            Object.assign(emptyItem(),{
                id: 8, parentId: 6, type: 7,
                title: 'Durchführung von Usability-Tests',
                regions: ['Support'],
                responsible: 'I. Horvat',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '3.1.2025', dateEnd: '23.12.2025',
                expanded: false,
                done: true,
                color: 'green',
            }),
            Object.assign(emptyItem(),{
                id: 9, parentId: 2, type: 2,
                title: 'Etappenziel 3: Marketing- und Vertriebskampagne vorbereiten',
                regions: ['Service', 'Logistik'],
                responsible: 'M. Benedetto',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateEnd: '12.12.2025',
                expanded: false,
                done: true,
                color: 'green',
            }),
            Object.assign(emptyItem(),{
                id: 10, parentId: 2, type: 2,
                title: 'Etappenziel 4: Launch und Post-Launch-Support',
                regions: ['Verkauf', 'Marketing'],
                responsible: 'K. Schneider',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '12.3.2025', dateEnd: '23.12.2025',
                expanded: false,
                color: 'orange',
            }),
            Object.assign(emptyItem(),{
                id: 11, parentId: 1, type: 8,
                title: 'Hauptziel: Optimierung der internen Kommunikation und Steigerung der Zusammenarbeit implement long name check lorem ipslump',
                regions: ['Führungsteam'],
                responsible: 'S. Fischer',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.2.2025', dateEnd: '23.12.2025',
                expanded: false,
                done: true,
                color: 'cyan',
            }),
            Object.assign(emptyItem(),{
                id: 12, parentId: 1,
                title: 'Hauptziel: Expansion in internationale Märkte und Aufbau einer globalen Markenpräsenz',
                regions: ['Produktionsleitung'],
                responsible: 'J. Depont',
                progress: '-10%',
                progressColor: 'red',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                expanded: false,
                color: 'purple',
            }),
            Object.assign(emptyItem(),{
                id: 13, type: 4,
                title: 'Steigerung der Kundenzufriedenheit und Bindung durch außergewöhnlichen Service',
                regions: ['Führungsteam'],
                responsible: 'I. Horvat',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                expanded: false,
                color: 'orange',
            }),
            Object.assign(emptyItem(),{
                id: 14, type: 14,
                title: 'Markenbekanntheit erhöhen und die Marktführerschaft im internationalen Umfeld ausbauen',
                regions: ['Führungsteam'],
                responsible: 'M. Benedetto',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateEnd: '23.12.2025',
                expanded: false,
                color: 'purple',
            }),
            Object.assign(emptyItem(),{
                id: 15, type: 12,
                title: 'Thema 01',
                regions: ['Produktionsleitung'],
                expanded: false,
                color: 'violet',
            }),
            Object.assign(emptyItem(),{
                id: 16, type: 13,
                title: 'Signal 001',
                regions: ['Verkauf'],
                expanded: false,
                color: 'violet',
            }),
        ]
    }
    return new Map(ls_.map(x => [x.id, x]))
}