export function getItems() {
    let ls_ = localStorage.getItem('items')
    if (ls_) {
        ls_ = JSON.parse(ls_)
    } else {
        ls_ = [
            {
                id: 1, parentId: null, type: 9,
                title: 'Initiative: Softwarelösungen für kleine Unternehmen',
                regions: ['Führungsteam'],
                responsible: 'S. Fischer',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: true,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'blue',
            },
            {
                id: 2, parentId: 1, type: 1,
                title: 'Hauptziel: Erfolgreiche Einführung eines neuen Softwareprodukts auf dem Markt',
                regions: ['Produktionsleitung', 'Marketing', 'Verkauf'],
                responsible: 'J. Depont',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: ['KC', 'OKR'],
                expanded: true,
                done: true,
                pinned: 5,
                team: [],
                category: [],
                anspruch: [],
                color: 'green',
            },
            {
                id: 3, parentId: 2, type: 2,
                title: 'Etappenziel 1: Marktforschung',
                regions: ['Verkauf'],
                responsible: 'I. Horvat',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateDays: '-5 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: true,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'orange',
            },
            {
                id: 4, parentId: 3, type: 3,
                title: 'Design und Prototyping des Produkts',
                regions: ['Logistik'],
                responsible: 'M. Benedetto',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '', dateDays: '', dateEnd: '23.12.2025',
                tags: ['KC'],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'purple',
            },
            {
                id: 5, parentId: 3, type: 6,
                title: 'Erstellung der Marketingstrategie',
                regions: ['Qualiätssicherung'],
                responsible: 'K. Schneider',
                progress: '-10%',
                progressColor: 'red',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: true,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'red',
            },
            {
                id: 6, parentId: 2, type: 4,
                title: 'Etappenziel 2: Produktentwicklung und Usability-Tests',
                regions: ['Social Media', 'Verkauf', 'Marketing'],
                responsible: 'S. Fischer',
                progress: '-10%',
                progressColor: 'red',
                dateStart: '', dateDays: '', dateEnd: '23.12.2025',
                tags: [],
                expanded: true,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'cyan',
            },
            {
                id: 7, parentId: 6, type: 5,
                title: 'Erarbeitung des ersten Softwareprototyps...',
                regions: ['Marketing', 'Verkauf'],
                responsible: 'J. Depont',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateDays: '-5 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'blue',
            },
            {
                id: 8, parentId: 6, type: 7,
                title: 'Durchführung von Usability-Tests',
                regions: ['Support'],
                responsible: 'I. Horvat',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: true,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'green',
            },
            {
                id: 9, parentId: 2, type: 2, 
                title: 'Etappenziel 3: Marketing- und Vertriebskampagne vorbereiten',
                regions: ['Service', 'Logistik'],
                responsible: 'M. Benedetto',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateDays: '-5 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: true,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'green',
            },
            {
                id: 10, parentId: 2, type: 2, 
                title: 'Etappenziel 4: Launch und Post-Launch-Support',
                regions: ['Verkauf', 'Marketing'],
                responsible: 'K. Schneider',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'orange',
            },
            {
                id: 11, parentId: 1, type: 8, 
                title: 'Hauptziel: Optimierung der internen Kommunikation und Steigerung der Zusammenarbeit im...',
                regions: ['Führungsteam'],
                responsible: 'S. Fischer',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: true,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'cyan',
            },
            {
                id: 12, parentId: 1, type: 1,
                title: 'Hauptziel: Expansion in internationale Märkte und Aufbau einer globalen Markenpräsenz',
                regions: ['Produktionsleitung'],
                responsible: 'J. Depont',
                progress: '-10%',
                progressColor: 'red',
                dateStart: '23.12.2025', dateDays: '126 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'purple',
            },
            {
                id: 13, parentId: null, type: 4,
                title: 'Steigerung der Kundenzufriedenheit und Bindung durch außergewöhnlichen Service',
                regions: ['Führungsteam'],
                responsible: 'I. Horvat',
                progress: '+50%',
                progressColor: 'orange',
                dateStart: '23.12.2025', dateDays: '125 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'orange',
            },
            {
                id: 14, parentId: null, type: 14,
                title: 'Markenbekanntheit erhöhen und die Marktführerschaft im internationalen Umfeld ausbauen',
                regions: ['Führungsteam'],
                responsible: 'M. Benedetto',
                progress: '+85%',
                progressColor: 'green',
                dateStart: '23.12.2025', dateDays: '126 Tg', dateEnd: '23.12.2025',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'purple',
            },
            {
                id: 15, parentId: null, type: 12,
                title: 'Thema 01',
                regions: ['Produktionsleitung'],
                responsible: '',
                progress: '',
                progressColor: '',
                dateStart: '', dateDays: '', dateEnd: '',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'violet',
            },
            {
                id: 16, parentId: null, type: 13,
                title: 'Signal 001',
                regions: ['Verkauf'],
                responsible: '',
                progress: '',
                progressColor: '',
                dateStart: '', dateDays: '', dateEnd: '',
                tags: [],
                expanded: false,
                done: false,
                pinned: 0,
                team: [],
                category: [],
                anspruch: [],
                color: 'violet',
            },
        ]
    }
    return new Map(ls_.map(x => [x.id, x]))
}