@WebApiSqlite_HostAddress = http://localhost:8080

GET {{WebApiSqlite_HostAddress}}/users/
Accept: application/json

###

GET {{WebApiSqlite_HostAddress}}/users/1
Accept: application/json

###

POST {{WebApiSqlite_HostAddress}}/users/
Accept: application/json

###
